<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $activationcode
 * @property integer $activated
 * @property string $registration_date
 * @property string $last_login_date
 * @property string $last_login_ip
 * @property integer $level
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password, email, activationcode, activated, registration_date, last_login_date, last_login_ip', 'required'),
			array('activated, level', 'numerical', 'integerOnly'=>true),
			array('username, password, email, activationcode, last_login_ip', 'length', 'max'=>255),
			array('level', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, email, activationcode, activated, registration_date, last_login_date, last_login_ip, level', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'activationcode' => Yii::t('app', 'Activationcode'),
			'activated' => Yii::t('app', 'Activated'),
			'registration_date' => Yii::t('app', 'Registration Date'),
			'last_login_date' => Yii::t('app', 'Last Login Date'),
			'last_login_ip' => Yii::t('app', 'Last Login Ip'),
			'level' => Yii::t('app', 'Level'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('activationcode', $this->activationcode, true);
		$criteria->compare('activated', $this->activated);
		$criteria->compare('registration_date', $this->registration_date, true);
		$criteria->compare('last_login_date', $this->last_login_date, true);
		$criteria->compare('last_login_ip', $this->last_login_ip, true);
		$criteria->compare('level', $this->level);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}